### ISSUE TITLE
[BUG] Unable to initialize shared memory: No such file or directory

### ISSUE THREAD

**Issue by ScriptSathi** [eunomia-bpf/bpftime#275]
**Describe the bug**

When using bpftrace with bpftime I got the below error

```txt
[error] [agent.cpp:105] Unable to initialize shared memory: No such file or directory
```

**To Reproduce**

Use Ubuntu Dockerfile, build the image and then run it with

```bash
docker run --rm -it \
-v /dev/shm:/dev/shm:rw -v /usr/src:/usr/src:ro \
-v /lib/modules/:/lib/modules:ro \
--privileged \
-v /sys/kernel/debug/:/sys/kernel/debug:rw  \
-v /sys/kernel/tracing:/sys/kernel/tracing:rw \
bpftime bash
```

then install bpftrace (no need to have the latest)

```bash
apt install bpftrace -y
```

Then run the test

```bash 
bpftime start bpftrace -e 'BEGIN { printf("hello world\n"); }'
```

**Expected behavior**

No error happen

* OS : ArchiLinux
* Version : 6.8.4-arch1-1

**Additional context**

I think the error come from this line https://github.com/eunomia-bpf/bpftime/blob/master/runtime/src/bpftime_shm_internal.cpp#L547

But I use the default shared memory name
https://github.com/eunomia-bpf/bpftime/blob/master/runtime/src/handler/handler_manager.hpp#L52

I probably have a wrong understanding of the origin, though ...

**Comment by Officeyutong** [comment]
You should use `bpftime load` to start bpftrace, not `bpftime start`

**Comment by ScriptSathi** [comment]
But then it goes to this issue...

https://github.com/eunomia-bpf/bpftime/issues/269

**Comment by Officeyutong** [comment]
Has this issue been solved now? If so, please close this issue @ScriptSathi

**Comment by ScriptSathi** [comment]
Well not really ...
I still can't use bpftime properly with bpftrace

Should I reopen the other one ?

**Comment by Officeyutong** [comment]
> bpftrace

**Comment by Officeyutong** [comment]
> Well not really ... I still can't use bpftime properly with bpftrace
> 
> Should I reopen the other one ?

Just open a new issue if you have any other problems
